version: "3.8"

services:
  database:
    container_name: database
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=nash
      - POSTGRES_PASSWORD=nashkim
      - POSTGRES_DB=fantasy
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: